language: node_js
node_js:
  - "0.8"
before_install:
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.1-beta1
  - export PATH=$PATH:`pwd`/bin
  - cd -
before_script:
  - phantomjs --version
  - casperjs --version
script: casperjs googleplus.js --username=altryne2 --password=THISISNOTMYPASSWORD --text="lalalalalaa| TechCrunch http://a-w.me/14PzvTR"
after_failure:
  - git checkout posts
  - git add .
  - git commit -am "adding stuff"
  - git push origin posts